export const FETCH_USERS = 'FETCH_USERS';
export const PAUSE_UPDATE = 'PAUSE_UPDATE';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const OPEN_USER_INFO = 'OPEN_USER_INFO';
export const CLOSE_USER_INFO = 'CLOSE_USER_INFO';
export const UPDATE_USER_INFO_DEFAULT_PERSONS = 'UPDATE_USER_INFO_DEFAULT_PERSONS';
export const OPEN_TAG_PEOPLE_DIALOG = 'OPEN_TAG_PEOPLE_DIALOG';
export const CLOSE_TAG_PEOPLE_DIALOG = 'CLOSE_TAG_PEOPLE_DIALOG';
export const SAVE_PEOPLE_TAGS = 'SAVE_PEOPLE_TAGS';

export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const CURRENT_IMAGE_CHANGE = 'CURRENT_IMAGE_CHANGE';
export const IMAGE_CLICK = 'IMAGE_CLICK';
export const LIGHTBOX_OPEN = 'LIGHTBOX_OPEN';
export const LIGHTBOX_CLOSE = 'LIGHTBOX_CLOSE';
export const LIGHTBOX_NEXT = 'LIGHTBOX_NEXT';
export const LIGHTBOX_PREV = 'LIGHTBOX_PREV';
export const DESELECT_ALL = 'DESELECT_ALL';

export const SHIFT_DOWN = 'SHIFT_DOWN';
export const SHIFT_UP = 'SHIFT_UP';
export const DEL_PRESSED = 'DEL_PRESSED';

export const DELETE_PHOTOS = 'DELETE_PHOTOS';
