
server:
    db_connection_string: ''
    static_dir: 'files'
    photos_dir: 'photos'

updater:
    pause: true

storage:
    storage_type: '',
    region_name: '',
    endpoint_url: '',
    access_key_id: '',
    secret_access_key: '',
    bucket: ''
    base_dir: ''

api_clients:
    base: 'https://<api_url>'
    version: '<version>'
    lang: en
    token: <token>
    user: <user_id>
    user_info_fields:
        - first_name
        - last_name

    group_info_fields:
        - city
